### ISSUE TITLE
skinchanger:loadSkin -- Ignores defaults and replaces everything.

### ISSUE THREAD

**Issue by iiAlphaWolf** [esx-framework/skinchanger#55]
Hello,

I'am trying to make something to work therefor i needed skinchanger. In the script (ill show down below) there is a line i added but it doenst seem to function right, at least i think. When i go in game and enable/start the script there arent any errors but i change to this random old women xD? while i was a configured male. How can i make sure the skinchanger only changes the things i wanted it to change, in this situation only the tshirt.. and not the whole char. Please help me

Kind regards,

Ralph Stoop

`
TriggerEvent('skinchanger:getSkin', function(skin)
    **TriggerEvent('skinchanger:loadSkin', {**
        tshirt_1     = 16,
    })

    print(json.encode(skin))
end)
`

**Comment by Gamernoobb** [comment]
Alkshdosve

**Comment by iiAlphaWolf** [comment]
Got it to work I used the default local to assign everything on top and made a specific set of combinations where I needed it

**Comment by iiAlphaWolf** [comment]
Van be closed
